/*  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms.  

Link to the problem - https://projecteuler.net/problem=2    */

#include<iostream>
using namespace std;

int main()
{
    int term=1, prev=0, sum=0;
    while(term<=4000000)
    {
        int temp = term;
        term = term + prev;
        prev = temp;

        if(term%2==0)
        {
            sum = sum + term;
        }
    }
    cout << sum;
}

// ANSWER: 4613732